---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: fluxcd
  namespace: fluxcd
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: fluxcd
  url: https://github.com/jufkes/marketalerts
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: fluxcd
  namespace: fluxcd
spec:
  interval: 10m0s
  path: ./clusters/crypto
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd
  validation: client
