apiVersion: v1
kind: ConfigMap
metadata:
  name: marketalerts-appyaml
data:
  application.yaml: |
    server:
      port: 8080

    spring:
      data:
        mongodb:
          host: mongodb.marketalerts.svc.cluster.local
          port: 27017
          database: market-alerts

    discord:
      webhook: ""