apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketalerts
  namespace: marketalerts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketalerts
  template:
    metadata:
      labels:
        app: marketalerts
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: marketalerts-api
        image: portr.ctl.io/private/marketalerts:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
          - mountPath: /application.yaml
            name: application-yaml
            subPath: application.yaml
            readOnly: true
      volumes:
        - name: application-yaml
          configMap:
            defaultMode: 420
            name: marketalerts-appyaml