apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: marketalerts
spec:
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
  type: ClusterIP