apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: marketalerts
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block