server:
  port: 8080
#mongodb
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: market-alerts

discord:
  webhook: ""

schedule.enabled: true

websocket:
  enabled: true
  url: wss://stream.binance.com:9443/ws/marketalerts
