name: Java CI

on: [push]

jobs:
  build:
    runs-on: self-hosted
    environment: portr

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker image
        run: docker build -t portr.ctl.io/private/marketalerts:1.0.${GITHUB_SHA::8} .

      - name: Publish latest image
        run: portr.ctl.io/private/marketalerts:1.0.${GITHUB_SHA::8}