name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: portr

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Build with Maven
        run: mvn clean install

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: portr.ctl.io
          username: ${{ secrets.PORTR_USERNAME }}
          password: ${{ secrets.PORTR_PASSWORD }}

      - name: Build Docker image
        run: docker build -t portr.ctl.io/private/marketalerts .

      - name: Publish latest image
        run: portr.ctl.io/private/marketalerts